### ISSUE TITLE
Thanks for your share,js challenge not work.

### ISSUE THREAD

**Issue by senioi** [azhuge233/SteamDB-FreeGames-dotnet#1]
can't get the html source.

**Comment by azhuge233** [comment]
![](https://user-images.githubusercontent.com/17763056/128492435-cbf5f639-b37e-49a1-8f3e-07682184a7d3.png)
Runs properly on my server.
I just updated the logging format, pull the repo and rebuild. If the error happens again, please provide the logs.
The program will ignore the games that are in weekend freetype.
Cloudflare challenge may detects your network, you probably should check on that also.
